const CART = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  UPDATE_CART_QUANTITY: 'UPDATE_CART_QUANTITY',
  IS_CARTITEM: 'IS_CARTITEM',
};

const APPSETTING = {
  GET_CONFIG: 'GET_CONFIG',
};

const PRODUCTS = {
  GET_HOME_PRODUCTS: 'GET_HOME_PRODUCTS',
  GET_PRODUCT_DETAIL: 'GET_PRODUCT_DETAIL',
  GET_RELATED_PRODUCTS: 'GET_RELATED_PRODUCTS',
};

export {CART, APPSETTING, PRODUCTS};
